pipeline{
  agent any
    stages{
      stage('dtabase container'){
        steps{
          sh 'sudo docker container rm -f mysql-db'
          sh 'sudo docker container run -dt --name mysql-db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=P@55word mysql:latest'
        }
      }
      stage('Docker build backend'){
        steps{
          sh 'sudo docker rmi -f backend'
          sh 'cd LMS-BE && sudo docker build -t backend .'
        }
      }
      stage('Docker container'){
        steps{
          sh 'sudo docker container rm -f be'
          sh 'sudo docker container run -dt --name be -p 8081:8080 backend'
        }
      }
    }
  }
